import { Pack, WordPair } from '@/types/game';

export const BUILT_IN_PACKS: Pack[] = [
  {
    id: 'desi-food',
    name: 'Food',
    description: 'Samosas, chaats, biryani, sweets and street snacks',
    category: 'Food',
    isBuiltIn: true,
    pairs: [
      { a: 'Samosa', b: 'Kachori' },
      { a: 'Jalebi', b: 'Imarti' },
      { a: 'Biryani', b: 'Pulao' },
      { a: 'Lassi', b: 'Chaas' },
      { a: 'Rasgulla', b: 'Gulabjamun' },
      { a: 'Dhokla', b: 'Khandvi' },
      { a: 'Dosa', b: 'Uttapam' },
      { a: 'Idli', b: 'Vada' },
      { a: 'Momos', b: 'Dimsum' },
      { a: 'Roti', b: 'Paratha' },
      { a: 'Naan', b: 'Kulcha' },
      { a: 'Kheer', b: 'Halwa' },
      { a: 'Rasmalai', b: 'Rabdi' },
      { a: 'Bhelpuri', b: 'Sevpuri' },
      { a: 'Kulfi', b: 'Falooda' },
      { a: 'Chai', b: 'Coffee' },
      { a: 'Pakora', b: 'Bhajiya' },
      { a: 'Paneer', b: 'Tofu' },
      { a: 'Papad', b: 'Khakhra' },
      { a: 'Peda', b: 'Barfi' },
      { a: 'Laddoo', b: 'Modak' },
    ],
  },
  {
    id: 'bollywood',
    name: 'Bollywood',
    description: 'Iconic movies, blockbusters, actors and villains',
    category: 'Entertainment',
    isBuiltIn: true,
    pairs: [
      { a: 'Sholay', b: 'Deewaar' },
      { a: 'Dangal', b: 'Sultan' },
      { a: 'Lagaan', b: 'Swades' },
      { a: 'Don', b: 'Dhoom' },
      { a: 'Krrish', b: 'Ra.One' },
      { a: 'Stree', b: 'Bhediya' },
      { a: 'Gadar', b: 'Border' },
      { a: 'Animal', b: 'Kabir-Singh' },
      { a: 'Bahubali', b: 'RRR' },
      { a: 'Pushpa', b: 'KGF' },
      { a: 'Mirzapur', b: 'Sacred-Games' },
      { a: 'Panchayat', b: 'Gullak' },
      { a: 'Mogambo', b: 'Gabbar' },
      { a: 'Kaal', b: 'Kancha' },
      { a: 'Circuit', b: 'Gogo' },
      { a: 'Babu-Rao', b: 'Majnu-Bhai' },
      { a: 'Dilwale', b: 'Kuch-Kuch-Hota-Hai' },
      { a: 'PK', b: '3-Idiots' },
      { a: 'Simmba', b: 'Singham' },
      { a: 'Jawan', b: 'Pathaan' },
      { a: 'Kick', b: 'Wanted' },
    ],
  },
  {
    id: 'cricket',
    name: 'Cricket',
    description: 'Cricket terms, IPL teams, legends and match situations',
    category: 'Sports',
    isBuiltIn: true,
    pairs: [
      { a: 'Kohli', b: 'Rohit' },
      { a: 'Dhoni', b: 'Sachin' },
      { a: 'Bumrah', b: 'Shami' },
      { a: 'Jadeja', b: 'Axar' },
      { a: 'Sehwag', b: 'Yuvraj' },
      { a: 'Pandya', b: 'Stokes' },
      { a: 'CSK', b: 'MI' },
      { a: 'RCB', b: 'KKR' },
      { a: 'Wankhede', b: 'Eden-Gardens' },
      { a: 'Yorker', b: 'Bouncer' },
      { a: 'Googly', b: 'Doosra' },
      { a: 'Cover-Drive', b: 'Pull-Shot' },
      { a: 'Helicopter-Shot', b: 'Scoop' },
      { a: 'Four', b: 'Six' },
      { a: 'LBW', b: 'Bowled' },
      { a: 'Stumping', b: 'Run-Out' },
      { a: 'Powerplay', b: 'Death-Overs' },
      { a: 'Spinner', b: 'Pacer' },
      { a: 'DRS', b: 'Umpire' },
      { a: 'Ashes', b: 'Border-Gavaskar' },
      { a: 'Super-Over', b: 'Tie' },
    ],
  },
  {
    id: 'shaadi',
    name: 'Shaadi',
    description: 'Indian weddings, festive rituals, attire and sweets',
    category: 'Culture',
    isBuiltIn: true,
    pairs: [
      { a: 'Sangeet', b: 'Mehendi' },
      { a: 'Baraat', b: 'Reception' },
      { a: 'Haldi', b: 'Roka' },
      { a: 'Diwali', b: 'Holi' },
      { a: 'Dussehra', b: 'Navratri' },
      { a: 'Garba', b: 'Dandiya' },
      { a: 'Bhangra', b: 'Gidda' },
      { a: 'Sherwani', b: 'Kurta' },
      { a: 'Lehenga', b: 'Saree' },
      { a: 'Dupatta', b: 'Stole' },
      { a: 'Jhumka', b: 'Payal' },
      { a: 'Bangles', b: 'Kada' },
      { a: 'Sindoor', b: 'Bindi' },
      { a: 'Mangalsutra', b: 'Necklace' },
      { a: 'Dulha', b: 'Dulhan' },
      { a: 'Pandit', b: 'Qazi' },
      { a: 'Dholak', b: 'Tabla' },
      { a: 'Diya', b: 'Candle' },
      { a: 'Patakha', b: 'Phooljhadi' },
      { a: 'Prasad', b: 'Bhog' },
      { a: 'Shagun', b: 'Gift' },
    ],
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Indian startups, corporate life, workplace slang and apps',
    category: 'Tech',
    isBuiltIn: true,
    pairs: [
      { a: 'Swiggy', b: 'Zomato' },
      { a: 'Blinkit', b: 'Zepto' },
      { a: 'Ola', b: 'Uber' },
      { a: 'Paytm', b: 'PhonePe' },
      { a: 'Jio', b: 'Airtel' },
      { a: 'Flipkart', b: 'Amazon' },
      { a: 'Infosys', b: 'TCS' },
      { a: 'Wipro', b: 'Cognizant' },
      { a: 'Zerodha', b: 'Groww' },
      { a: 'Slack', b: 'Teams' },
      { a: 'Zoom', b: 'Meet' },
      { a: 'Frontend', b: 'Backend' },
      { a: 'Python', b: 'Java' },
      { a: 'React', b: 'Vue' },
      { a: 'Appraisal', b: 'Hike' },
      { a: 'Standup', b: 'Retro' },
      { a: 'Sprint', b: 'Backlog' },
      { a: 'WFH', b: 'WFO' },
      { a: 'CTC', b: 'In-Hand' },
      { a: 'ESOP', b: 'Bonus' },
      { a: 'Bug', b: 'Feature' },
    ],
  },
  {
    id: 'nostalgia',
    name: 'Nostalgia',
    description: 'Childhood memories, school items, vintage desi staples',
    category: 'Daily Life',
    isBuiltIn: true,
    pairs: [
      { a: 'Rasna', b: 'Roohafza' },
      { a: 'Bournvita', b: 'Horlicks' },
      { a: 'Complan', b: 'Boost' },
      { a: 'Frooti', b: 'Maaza' },
      { a: 'Natraj', b: 'Apsara' },
      { a: 'Dettol', b: 'Savlon' },
      { a: 'Boroline', b: 'Boroplus' },
      { a: 'Vicco', b: 'Colgate' },
      { a: 'Parle-G', b: 'Marie-Gold' },
      { a: 'Crax', b: 'Cheetos' },
      { a: 'Doordarshan', b: 'DishTV' },
      { a: 'Flames', b: 'Tic-Tac-Toe' },
      { a: 'Tuition', b: 'Coaching' },
      { a: 'Chappal', b: 'Sandals' },
      { a: 'Cooler', b: 'Fan' },
      { a: 'Inverter', b: 'Generator' },
      { a: 'Gullak', b: 'Piggybank' },
      { a: 'Carrom', b: 'Ludo' },
      { a: 'Antakshari', b: 'Dumb-Charades' },
      { a: 'Kite', b: 'Manjha' },
      { a: 'Gully-Cricket', b: 'Stump-Ball' },
    ],
  },
  {
    id: 'travel',
    name: 'Travel',
    description: 'Indian tourist spots, transport, hills and transit',
    category: 'Travel',
    isBuiltIn: true,
    pairs: [
      { a: 'Goa', b: 'Gokarna' },
      { a: 'Manali', b: 'Shimla' },
      { a: 'Rishikesh', b: 'Haridwar' },
      { a: 'Jaipur', b: 'Udaipur' },
      { a: 'Varanasi', b: 'Prayagraj' },
      { a: 'Ooty', b: 'Kodaikanal' },
      { a: 'Ladakh', b: 'Spiti' },
      { a: 'Kedarnath', b: 'Badrinath' },
      { a: 'Darjeeling', b: 'Gangtok' },
      { a: 'Kasol', b: 'Tirthan' },
      { a: 'Pondicherry', b: 'Mahabalipuram' },
      { a: 'Agra', b: 'Delhi' },
      { a: 'Amritsar', b: 'Chandigarh' },
      { a: 'Munnar', b: 'Wayanad' },
      { a: 'Hampi', b: 'Badami' },
      { a: 'Metro', b: 'Local-Train' },
      { a: 'Auto', b: 'Cab' },
      { a: 'Rajdhani', b: 'Shatabdi' },
      { a: 'Vande-Bharat', b: 'Tejas' },
      { a: 'Houseboat', b: 'Shikara' },
      { a: 'Tatkal', b: 'General' },
    ],
  },
  {
    id: 'superheroes',
    name: 'Superheroes',
    description: 'Famous heroes, powers, villains and comic characters',
    category: 'Pop Culture',
    isBuiltIn: true,
    pairs: [
      { a: 'Batman', b: 'Ironman' },
      { a: 'Superman', b: 'Thor' },
      { a: 'Spiderman', b: 'Deadpool' },
      { a: 'Hulk', b: 'Thing' },
      { a: 'Flash', b: 'Quicksilver' },
      { a: 'Aquaman', b: 'Namor' },
      { a: 'Shaktimaan', b: 'Krrish' },
      { a: 'Joker', b: 'Riddler' },
      { a: 'Thanos', b: 'Darkseid' },
      { a: 'Loki', b: 'Magneto' },
      { a: 'Venom', b: 'Carnage' },
      { a: 'Wolverine', b: 'Sabretooth' },
      { a: 'Groot', b: 'Rocket' },
      { a: 'Hawkeye', b: 'Green-Arrow' },
      { a: 'Vibranium', b: 'Adamantium' },
      { a: 'Kryptonite', b: 'Infinity-Stone' },
      { a: 'Mjolnir', b: 'Stormbreaker' },
      { a: 'Batmobile', b: 'Quinjet' },
      { a: 'Avengers', b: 'Justice-League' },
      { a: 'G.One', b: 'Ra.One' },
      { a: 'Robin', b: 'Nightwing' },
    ],
  },
  {
    id: 'cartoons',
    name: 'Cartoons',
    description: 'Classic cartoons, animated shows and characters',
    category: 'Entertainment',
    isBuiltIn: true,
    pairs: [
      { a: 'Doraemon', b: 'Shinchan' },
      { a: 'Nobita', b: 'Gian' },
      { a: 'Bheem', b: 'Kalia' },
      { a: 'Motu', b: 'Patlu' },
      { a: 'Oggy', b: 'Jack' },
      { a: 'Tom', b: 'Jerry' },
      { a: 'Scooby', b: 'Courage' },
      { a: 'Ben-10', b: 'Generator-Rex' },
      { a: 'SpongeBob', b: 'Patrick' },
      { a: 'Popeye', b: 'Bluto' },
      { a: 'Mickey', b: 'Donald' },
      { a: 'Dexter', b: 'DeeDee' },
      { a: 'Blossom', b: 'Bubbles' },
      { a: 'Johnny-Bravo', b: 'Samurai-Jack' },
      { a: 'Hattori', b: 'Perman' },
      { a: 'Pokemon', b: 'Digimon' },
      { a: 'Pikachu', b: 'Raichu' },
      { a: 'Phineas', b: 'Ferb' },
      { a: 'Bugs-Bunny', b: 'Daffy-Duck' },
      { a: 'Kiteretsu', b: 'Doraemon' },
      { a: 'Beyblade', b: 'Bakugan' },
    ],
  },
  {
    id: 'series',
    name: 'Series',
    description: 'Top bingeable TV series and web shows',
    category: 'Entertainment',
    isBuiltIn: true,
    pairs: [
      { a: 'Breaking-Bad', b: 'Better-Call-Saul' },
      { a: 'Game-of-Thrones', b: 'House-of-the-Dragon' },
      { a: 'Stranger-Things', b: 'Dark' },
      { a: 'Friends', b: 'HIMYM' },
      { a: 'The-Office', b: 'Brooklyn-99' },
      { a: 'Mirzapur', b: 'Sacred-Games' },
      { a: 'Panchayat', b: 'Gullak' },
      { a: 'Family-Man', b: 'Special-OPS' },
      { a: 'Asur', b: 'Paatal-Lok' },
      { a: 'Farzi', b: 'Taaza-Khabar' },
      { a: 'Kota-Factory', b: 'Aspirants' },
      { a: 'Money-Heist', b: 'Lupin' },
      { a: 'Squid-Game', b: 'Alice-in-Borderland' },
      { a: 'Sherlock', b: 'Mindhunter' },
      { a: 'Narcos', b: 'Peaky-Blinders' },
      { a: 'Suits', b: 'Billions' },
      { a: 'The-Boys', b: 'Invincible' },
      { a: 'Wednesday', b: 'Euphoria' },
      { a: 'Succession', b: 'Mad-Men' },
      { a: 'Dark', b: '1899' },
      { a: 'Flea-Bag', b: 'Modern-Love' },
    ],
  },
  {
    id: 'companies',
    name: 'Companies',
    description: 'Famous brands, tech giants and market competitors',
    category: 'Business',
    isBuiltIn: true,
    pairs: [
      { a: 'Swiggy', b: 'Zomato' },
      { a: 'Blinkit', b: 'Zepto' },
      { a: 'Google', b: 'Microsoft' },
      { a: 'Apple', b: 'Samsung' },
      { a: 'Ola', b: 'Uber' },
      { a: 'Flipkart', b: 'Amazon' },
      { a: 'Infosys', b: 'TCS' },
      { a: 'Wipro', b: 'HCL' },
      { a: 'Jio', b: 'Airtel' },
      { a: 'Tata', b: 'Adani' },
      { a: 'Paytm', b: 'PhonePe' },
      { a: 'Nike', b: 'Adidas' },
      { a: 'Puma', b: 'Reebok' },
      { a: 'Netflix', b: 'Prime-Video' },
      { a: 'Hotstar', b: 'SonyLIV' },
      { a: 'Zerodha', b: 'Groww' },
      { a: 'Nykaa', b: 'Purplle' },
      { a: 'Coke', b: 'Pepsi' },
      { a: 'McDonalds', b: 'Burger-King' },
      { a: 'Starbucks', b: 'Costa' },
      { a: 'Zudio', b: 'Trends' },
    ],
  },
  {
    id: 'anime',
    name: 'Anime',
    description: 'Anime titles, heroes, rivals and powers',
    category: 'Pop Culture',
    isBuiltIn: true,
    pairs: [
      { a: 'Naruto', b: 'Sasuke' },
      { a: 'Goku', b: 'Vegeta' },
      { a: 'Luffy', b: 'Zoro' },
      { a: 'Light', b: 'L' },
      { a: 'Eren', b: 'Levi' },
      { a: 'Tanjiro', b: 'Zenitsu' },
      { a: 'Gojo', b: 'Sukuna' },
      { a: 'Saitama', b: 'Genos' },
      { a: 'Ichigo', b: 'Aizen' },
      { a: 'Deku', b: 'Bakugo' },
      { a: 'Kaneki', b: 'Touka' },
      { a: 'Edward', b: 'Mustang' },
      { a: 'Gon', b: 'Killua' },
      { a: 'Rasengan', b: 'Chidori' },
      { a: 'Sharingan', b: 'Byakugan' },
      { a: 'Super-Saiyan', b: 'Ultra-Instinct' },
      { a: 'Bankai', b: 'Domain-Expansion' },
      { a: 'Death-Note', b: 'Code-Geass' },
      { a: 'Bleach', b: 'Naruto' },
      { a: 'One-Piece', b: 'Dragon-Ball' },
      { a: 'Demon-Slayer', b: 'Jujutsu-Kaisen' },
    ],
  },
];

export function getRandomPairFromPacks(
  packs: Pack[],
  excludeWord?: string
): { pair: { a: string; b: string }; pack: Pack } {
  if (!packs || packs.length === 0) {
    packs = [BUILT_IN_PACKS[0]];
  }

  // Collect all available pairs across selected packs
  const candidatePairs: { pair: WordPair; pack: Pack }[] = [];
  packs.forEach((pack) => {
    pack.pairs.forEach((p) => {
      candidatePairs.push({ pair: p, pack });
    });
  });

  // Filter out recently used word pair if more than 1 pair exists
  let eligible = candidatePairs;
  if (excludeWord && candidatePairs.length > 1) {
    const filtered = candidatePairs.filter(
      (item) => item.pair.a !== excludeWord && item.pair.b !== excludeWord
    );
    if (filtered.length > 0) {
      eligible = filtered;
    }
  }

  const selected = eligible[Math.floor(Math.random() * eligible.length)];
  const { pair, pack } = selected;

  // Randomly swap a and b so civilians and undercovers aren't predictable
  const finalPair =
    Math.random() > 0.5
      ? { a: pair.a, b: pair.b }
      : { a: pair.b, b: pair.a };

  return { pair: finalPair, pack };
}

export function getRandomPairFromPack(pack: Pack, excludeWord?: string): { a: string; b: string } {
  return getRandomPairFromPacks([pack], excludeWord).pair;
}
